[build]
  command = "npm run build"
  functions = "lambda"

[[redirects]]
  from = "/toggle-theme*"
  to = "/toggle-theme"
  status = 200

[[redirects]]
  from = "/*"
  to = "/"
  status = 200

[[redirects]]
  from = "/blog*"
  to = "/blog"
  status = 200

[[redirects]]
  from = "/sobre*"
  to = "/sobre"
  status = 200

[[redirects]]
  from = "/typescript*"
  to = "/typescript"
  status = 200

[[redirects]]
  from = "/python*"
  to = "/python"
  status = 200
