[build]
  command = "npm run start"
  functions = "lambda"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
[build]
  command = "npm run start"

[[redirects]]
  from = "/toggle-theme*"
  to = "/toggle-theme"
  status = 200

[[redirects]]
  from = "/*"
  to = "/404"
  status = 404

[[redirects]]
  from = "/blog*"
  to = "/blog"
  status = 200

[[redirects]]
  from = "/sobre*"
  to = "/sobre"
  status = 200

[[redirects]]
  from = "/typescript*"
  to = "/typescript"
  status = 200

[[redirects]]
  from = "/python*"
  to = "/python"
  status = 200
