[functions]
  external_node_modules = ["express"]
  node_bundler = "esbuild"
[[redirects]]
  force = true
  from = "/toggle-theme*"
  from = "/*"
  from = "/blog*"
  from = "/sobre*"
  from = "/typescript*"
  from = "/python*"
  

  status = 200
  to = "/.netlify/functions/api/:splat"
